#!/usr/bin/env bash


# TODO
# Checker les différents outils
# - Déplacer le script checktools dans le dir d'install
# - décoreller le script de la "liste d'outils"
# - révoir une "checktool" par défaut et la possibilité de faire un "checktool" spécifique (ex: pour git vérifier qu'on a tig et/ou d'autres outils)

# Pour chaque outil, prévoir un script d'install avec les modes suivants
# - Mode normal : executer l'isntall si n'existe pas
# - Mode dry-run : print du script
# - Mode reinstall : exécuter l'install même si l'outil est déjà installé

install()
{

echo "Installing ..."
INSTALL_DIR="$HOME/.mine/install.d"

echo $INSTALL_DIR

PROFILE="$HOME/.profile"
cat <<'__EOF__' >>"$PROFILE"
# Load mine settings
source ${HOME}/.mine/etc/profile
__EOF__

# GIT
(cd "${HOME}" && cp .mine/etc/git/.gitconfig.template .gitconfig)

# BIN
find ./bin -type f -exec chmod +x {} \;	
}


if [[ -z "$INSTALLED" && {INSTALLED} ]]; then
  echo "installing"
  install
  source $PROFILE
  check_tools
fi
