#!/usr/bin/env bash

# TODO : mine
# Créer un script qui me permet de jouer des soucsi-scripts spécifiques à mes besoins
# Deux fonction principales 
# - mine install/tool-checking : pour installer les principaux outils
# - mine list : pour avoir la liste des scripts custom disponibles

# Voir ces ressources en inspiration d'un script avec des sub commands
# https://stackoverflow.com/questions/37257551/defining-subcommands-that-take-arguments-in-bash
# https://gist.github.com/waylan/4080362

# listes des scripts / idées
# - mine alias : permet de maintenir une liste d'alias
# - mine ssh-connect : aujourd'hui ma fonction custom la plus utile
# - mine secrets : permet de maintenir des secrests, non visibles sous git
# - mine env : permet de maintenir les variables d'environement, aujourd'hui dans 'profile'

# TODO: install
# Checker les différents outils
# - Déplacer le script checktools dans le dir d'install
# - décoreller le script de la "liste d'outils"
# - révoir une "checktool" par défaut et la possibilité de faire un "checktool" spécifique (ex: pour git vérifier qu'on a tig et/ou d'autres outils)

# Pour chaque outil, prévoir un script d'install avec les modes suivants
# - Mode normal : executer l'isntall si n'existe pas
# - Mode dry-run : print du script
# - Mode reinstall : exécuter l'install même si l'outil est déjà installé

# INSTALL de poste from scratch : 
 1  pwd
    2  ll
    3  mkdir .ssh
    4  cd .ssh/
    5  ssh-keygen -t ed25519 -C "fabien.hiegel@gmail.com"
    6  cat id_gh_win.pub
    7  eval $(ssh-agent -s) && find  ~/.ssh -name "id_*" -exec ssh-add {} \;
    8  cd
    9  git clone git@github.com:fhiegel/home.git .mine
   10  ll
   11  history
   12  mkdir -p .data/obsidian
   13  mkdir --help
   14  mkdir -p develop/workspaces/mine
   15  mkdir -p develop/workspaces/shodo develop/tools
   16  ll develop/
   17  cd .mine/
   18  cd
   19  cd .data/obsidian/
   20  git clone git@github.com:fhiegel/home.git .mine
   21  rm -rf .mine
   22  git clone git@github.com:de-dale/spherier-obsidian.git
   23  cd -
   24  (cd ~/.data/obsidian/ && git pull)
   # TODO : script git-obsidian
   25  (cd ~/.data/obsidian/spherier-obsidian/ && git pull)
   26  history
