#!/usr/bin/env bash

#
# HOME CONFIGURATION
#
if [ -z "${HOME_DIR}" ] ; then
    export HOME_DIR="$(readlink -f ~)"
fi
alias home="cd ${HOME_DIR}"

# IF WSL, configure windows home directory
if [ -n "${WSL_DISTRO_NAME}" ] ; then
    export WIN_HOME_DIR=$(wslpath "$(wslvar USERPROFILE)")
    alias win-home="cd ${WIN_HOME_DIR}"
fi

#
# MINE HOME
#
export MINE_HOME="${HOME_DIR}/.mine"
export MINE_DIR="${HOME_DIR}/.mine"
alias mine="cd ${MINE_HOME}"
export PATH="${MINE_HOME}/bin/:$PATH"

#
# DEV folders
#
export DEV_HOME="${HOME_DIR}/develop"
export DEV_WORKSPACE="${DEV_HOME}/workspaces"
export DEV_TOOLS="${DEV_HOME}/tools"
export DEV_MINE="${DEV_HOME}/mine"

[[ -d "${DEV_HOME}" ]] || mkdir -p "${DEV_HOME}"
[[ -d "${DEV_WORKSPACE}" ]] || mkdir -p "${DEV_WORKSPACE}"
[[ -d "${DEV_TOOLS}" ]] || mkdir -p "${DEV_TOOLS}"
[[ -d "${DEV_MINE}" ]] || mkdir -p "${DEV_MINE}"

alias dev="cd ${DEV_HOME}"
alias dev-work="cd ${DEV_WORKSPACE}"
alias dev-tools="cd ${DEV_TOOLS}"
alias dev-mine="cd ${DEV_MINE}"

export PATH="${TOOLS}/bin/:$PATH"

#
# SECRETS
#
load_secrets ()
{
  export MINE_SECRETS="${MINE_HOME}/etc/secrets"
  [[ -d "${MINE_SECRETS}" ]] || mkdir -p "${MINE_SECRETS}"
  for file in $(echo ${MINE_SECRETS}/*.env); do
    [[ -e "${file}" ]] && . "${file}"
  done
}
load_secrets

#
# Auto load 'autoload.d' content
# autoload.d
#   Shell dependent settings
#
autoload_d ()
{
  local file=
  for file in $(echo ${MINE_HOME}/etc/autoload.d/*); do
    [ -e "${file}" ] && . "${file}"
  done
}
autoload_d
