#!/bin/sh
#
#
NC='\033[0m' # No Color
RED='\033[0;31m'
GREEN='\033[0;32m'
indent='	'

filesWithTodo=`git diff HEAD --name-only --diff-filter=A -G '// TODO'`
if [ -n "${filesWithTodo}" ];
then
	cat <<- EOF
Commit interdit ! Les fichiers suivants contiennent encore des TODOs :

`while read fileWithTodo ; do
    echo -e "$indent$RED$fileWithTodo$NC"
done <<< $filesWithTodo`

Résolvez, ou finissez ces TODOs avant de committer !
EOF
else 
	echo -e "$GREEN"
	echo "You are allowed to commit !";
	echo -e "$NC"
fi
