#!/bin/bash

# Get all keybindings on your computer :
# gsettings list-recursively org.gnome.desktop.wm.keybinding

# Creates a backup
# gsettings list-recursively org.gnome.desktop.wm.keybinding | sort > keybindings.bak 

# 'keybindings' are modified output of command 
# 'gsettings list-recursively org.gnome.desktop.wm.keybinding'

read -r -d '' keybindings <<- EOL
     activate-window-menu ['<Super>space']
     always-on-top []
     begin-move []
     begin-resize []
     close ['<Alt>F4']
     cycle-group ['<Super>F6']
     cycle-group-backward ['<Super><Shift>F6']
     cycle-panels-backward ['<Super><Shift><Control>Escape']
     cycle-panels ['<Super><Control>Escape']
     cycle-windows ['<Super>Escape']
     cycle-windows-backward ['<Shift><Super>Escape']
     lower []
     maximize-horizontally []
     maximize ['<Super>Up']
     maximize-vertically []
     minimize ['<Super>h']
     move-to-center []
     move-to-corner-ne []
     move-to-corner-nw []
     move-to-corner-se []
     move-to-corner-sw []
     move-to-monitor-down ['<Super><Shift>Down']
     move-to-monitor-left ['<Super><Shift>Left']
     move-to-monitor-right ['<Super><Shift>Right']
     move-to-monitor-up ['<Super><Shift>Up']
     move-to-side-e []
     move-to-side-n []
     move-to-side-s []
     move-to-side-w []
     move-to-workspace-10 []
     move-to-workspace-11 []
     move-to-workspace-12 []
     move-to-workspace-1 ['<Super><Shift>Home']
     move-to-workspace-2 []
     move-to-workspace-3 []
     move-to-workspace-4 []
     move-to-workspace-5 []
     move-to-workspace-6 []
     move-to-workspace-7 []
     move-to-workspace-8 []
     move-to-workspace-9 []
     move-to-workspace-down ['<Super><Control><Shift>Down','<Super><Shift>Page_Down']
     move-to-workspace-last ['<Super><Control><Shift>End']
     move-to-workspace-left ['<Super><Control><Shift>Left']
     move-to-workspace-right ['<Super><Control><Shift>Right']
     move-to-workspace-up ['<Super><Control><Shift>Up','<Super><Shift>Page_Up']
     panel-main-menu ['<Super>F1']
     panel-run-dialog ['<Super>F2']
     raise []
     raise-or-lower []
EOL

echo "$keybindings" | while read -r keybinding ; do 
  echo $keybinding;
  gsettings set org.gnome.desktop.wm.keybindings $keybinding;
done
